2020-04-28 02:40:39.127 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,9} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,9},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.359.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.130 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,8} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,8},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.358.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.131 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,7} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,7},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.357.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.152 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,6} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,6},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.356.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.157 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,5} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,5},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.355.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.162 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,4} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,4},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.354.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.167 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,3} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,3},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.353.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.168 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,2} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,2},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.352.0> exit with reason shutdown in context shutdown_error
2020-04-28 02:40:39.168 [error] <0.350.0> Supervisor {<0.350.0>,'Elixir.DBConnection.ConnectionPool.Pool'} had child {'Elixir.Postgrex.Protocol',<0.349.0>,1} started with 'Elixir.DBConnection.Connection':start_link('Elixir.Postgrex.Protocol', [{pool_index,1},{types,'Elixir.Postgrex.DefaultTypes'},{port,5432},{repo,'Elixir.Microservice2.Repo'},...], <0.349.0>, #Ref<0.2654671783.217448449.78869>) at <0.351.0> exit with reason shutdown in context shutdown_error
