2020-04-27 01:24:28.170 [error] <0.508.0> gen_server <0.508.0> terminated with reason: {socket_error,timeout}
2020-04-27 01:24:28.171 [error] <0.504.0> gen_server <0.504.0> terminated with reason: {socket_error,timeout}
2020-04-27 01:24:28.339 [error] <0.504.0> CRASH REPORT Process <0.504.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 01:24:28.341 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.503.0>, {amqp_params_network,<<"guest">>,<<"TvLAljIZ2ITgK3j3UjJr8OLVGo9iPvp/sUu+2A/sEoUCsNo0qbNJwlkG5jy4qP...">>,...}) at <0.504.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 01:24:28.341 [error] <0.502.0> Supervisor {<0.502.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.503.0>, {amqp_params_network,<<"guest">>,<<"TvLAljIZ2ITgK3j3UjJr8OLVGo9iPvp/sUu+2A/sEoUCsNo0qbNJwlkG5jy4qP...">>,...}) at <0.504.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 01:24:28.348 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.513.0> exit with reason shutdown in context child_terminated
2020-04-27 01:24:28.581 [error] <0.407.0> gen_server <0.407.0> terminated with reason: {socket_error,timeout}
2020-04-27 01:24:28.582 [error] <0.402.0> gen_server <0.402.0> terminated with reason: {socket_error,timeout}
2020-04-27 01:24:28.777 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 01:24:28.796 [error] <0.400.0> Supervisor {<0.400.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.401.0>, {amqp_params_network,<<"guest">>,<<"furtz7uP3lpLnpOdHcPxjY8PsOcgLRWbC37Va4I9uvkVsbtz2tuBH7pmzQFXYe...">>,...}) at <0.402.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 01:24:28.796 [error] <0.400.0> Supervisor {<0.400.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.401.0>, {amqp_params_network,<<"guest">>,<<"furtz7uP3lpLnpOdHcPxjY8PsOcgLRWbC37Va4I9uvkVsbtz2tuBH7pmzQFXYe...">>,...}) at <0.402.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:18:35.010 [error] <0.614.0> gen_server <0.614.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:18:35.010 [error] <0.610.0> gen_server <0.610.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:18:35.010 [error] <0.614.0> CRASH REPORT Process <0.614.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:18:35.011 [error] <0.609.0> Supervisor {<0.609.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.82>, <0.610.0>, <0.612.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62798 -> 127.0.0.1:5672">>) at <0.614.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:18:35.011 [error] <0.609.0> Supervisor {<0.609.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.82>, <0.610.0>, <0.612.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62798 -> 127.0.0.1:5672">>) at <0.614.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:18:35.011 [error] <0.610.0> CRASH REPORT Process <0.610.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:18:35.011 [error] <0.608.0> Supervisor {<0.608.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.609.0>, {amqp_params_network,<<"guest">>,<<"fgBmM5oE43c0G0mPPNMmMzPDcBfBmsxHqv8XVDQmcxT5lZ+0B3nZkFb9Scnl4b...">>,...}) at <0.610.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:18:35.012 [error] <0.608.0> Supervisor {<0.608.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.609.0>, {amqp_params_network,<<"guest">>,<<"fgBmM5oE43c0G0mPPNMmMzPDcBfBmsxHqv8XVDQmcxT5lZ+0B3nZkFb9Scnl4b...">>,...}) at <0.610.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:18:35.019 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.607.0> exit with reason shutdown in context child_terminated
2020-04-27 02:18:35.208 [error] <0.20794.0> gen_server <0.20794.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:18:35.210 [error] <0.20794.0> CRASH REPORT Process <0.20794.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:18:35.211 [error] <0.20790.0> gen_server <0.20790.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:18:35.213 [error] <0.20789.0> Supervisor {<0.20789.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.20>, <0.20790.0>, <0.20792.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62799 -> 127.0.0.1:5672">>) at <0.20794.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:18:35.213 [error] <0.20789.0> Supervisor {<0.20789.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.20>, <0.20790.0>, <0.20792.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62799 -> 127.0.0.1:5672">>) at <0.20794.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:18:35.213 [error] <0.20790.0> CRASH REPORT Process <0.20790.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:18:35.219 [error] <0.20788.0> Supervisor {<0.20788.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20789.0>, {amqp_params_network,<<"guest">>,<<"xvosJKJg6rvL/u4q0ju5AN7SunI9kBXlxx9lkPfYtJAE59wZ8XuROyFIQIvtoB...">>,...}) at <0.20790.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:18:35.220 [error] <0.20788.0> Supervisor {<0.20788.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20789.0>, {amqp_params_network,<<"guest">>,<<"xvosJKJg6rvL/u4q0ju5AN7SunI9kBXlxx9lkPfYtJAE59wZ8XuROyFIQIvtoB...">>,...}) at <0.20790.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:57:15.009 [error] <0.629.0> gen_server <0.629.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:57:15.009 [error] <0.629.0> CRASH REPORT Process <0.629.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:57:15.197 [error] <0.20808.0> gen_server <0.20808.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:57:15.010 [error] <0.625.0> gen_server <0.625.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:57:15.010 [error] <0.625.0> CRASH REPORT Process <0.625.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:57:15.011 [error] <0.623.0> Supervisor {<0.623.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.624.0>, {amqp_params_network,<<"guest">>,<<"ovqcIglEHnSOwSNaajDMIaWZ513aspLUW4v0WaBVs9Xy5QsBO83rUOPlwp/waO...">>,...}) at <0.625.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:57:15.013 [error] <0.623.0> Supervisor {<0.623.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.624.0>, {amqp_params_network,<<"guest">>,<<"ovqcIglEHnSOwSNaajDMIaWZ513aspLUW4v0WaBVs9Xy5QsBO83rUOPlwp/waO...">>,...}) at <0.625.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:57:15.013 [error] <0.624.0> Supervisor {<0.624.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.83>, <0.625.0>, <0.627.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62828 -> 127.0.0.1:5672">>) at <0.629.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:57:15.013 [error] <0.624.0> Supervisor {<0.624.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.83>, <0.625.0>, <0.627.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62828 -> 127.0.0.1:5672">>) at <0.629.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:57:15.197 [error] <0.20808.0> CRASH REPORT Process <0.20808.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:57:15.024 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.622.0> exit with reason shutdown in context child_terminated
2020-04-27 02:57:15.198 [error] <0.20804.0> gen_server <0.20804.0> terminated with reason: {socket_error,timeout}
2020-04-27 02:57:15.198 [error] <0.20803.0> Supervisor {<0.20803.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.21>, <0.20804.0>, <0.20806.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62829 -> 127.0.0.1:5672">>) at <0.20808.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:57:15.199 [error] <0.20803.0> Supervisor {<0.20803.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.21>, <0.20804.0>, <0.20806.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62829 -> 127.0.0.1:5672">>) at <0.20808.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 02:57:15.201 [error] <0.20804.0> CRASH REPORT Process <0.20804.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 02:57:15.201 [error] <0.20802.0> Supervisor {<0.20802.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20803.0>, {amqp_params_network,<<"guest">>,<<"7WOS/JenSRFETaOPTkH3g5eU8xrZEZpNXo9XBgFen8GVYmV53Xxe0GaSjuNUqo...">>,...}) at <0.20804.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 02:57:15.202 [error] <0.20802.0> Supervisor {<0.20802.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20803.0>, {amqp_params_network,<<"guest">>,<<"7WOS/JenSRFETaOPTkH3g5eU8xrZEZpNXo9XBgFen8GVYmV53Xxe0GaSjuNUqo...">>,...}) at <0.20804.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 03:51:22.006 [error] <0.644.0> gen_server <0.644.0> terminated with reason: {socket_error,timeout}
2020-04-27 03:51:22.075 [error] <0.20820.0> gen_server <0.20820.0> terminated with reason: {socket_error,timeout}
2020-04-27 03:51:22.006 [error] <0.640.0> gen_server <0.640.0> terminated with reason: {socket_error,timeout}
2020-04-27 03:51:22.006 [error] <0.644.0> CRASH REPORT Process <0.644.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 03:51:22.007 [error] <0.639.0> Supervisor {<0.639.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.84>, <0.640.0>, <0.642.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62857 -> 127.0.0.1:5672">>) at <0.644.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 03:51:22.007 [error] <0.639.0> Supervisor {<0.639.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.84>, <0.640.0>, <0.642.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62857 -> 127.0.0.1:5672">>) at <0.644.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 03:51:22.008 [error] <0.640.0> CRASH REPORT Process <0.640.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 03:51:22.022 [error] <0.638.0> Supervisor {<0.638.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.639.0>, {amqp_params_network,<<"guest">>,<<"XiRepjeT2FyZkr7i6GmuUaLIsNTHd/1pOBJ8bgwK4Wn+SuqpRSQA3U7TfHXt4f...">>,...}) at <0.640.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 03:51:22.023 [error] <0.638.0> Supervisor {<0.638.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.639.0>, {amqp_params_network,<<"guest">>,<<"XiRepjeT2FyZkr7i6GmuUaLIsNTHd/1pOBJ8bgwK4Wn+SuqpRSQA3U7TfHXt4f...">>,...}) at <0.640.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 03:51:22.023 [error] <0.638.0> Supervisor {<0.638.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.639.0> exit with reason shutdown in context shutdown_error
2020-04-27 03:51:22.023 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.637.0> exit with reason shutdown in context child_terminated
2020-04-27 03:51:22.075 [error] <0.20820.0> CRASH REPORT Process <0.20820.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 03:51:22.076 [error] <0.20815.0> Supervisor {<0.20815.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.22>, <0.20816.0>, <0.20818.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62858 -> 127.0.0.1:5672">>) at <0.20820.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 03:51:22.076 [error] <0.20815.0> Supervisor {<0.20815.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.22>, <0.20816.0>, <0.20818.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62858 -> 127.0.0.1:5672">>) at <0.20820.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 03:51:22.076 [error] <0.20816.0> gen_server <0.20816.0> terminated with reason: {socket_error,timeout}
2020-04-27 03:51:22.078 [error] <0.20816.0> CRASH REPORT Process <0.20816.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 03:51:22.079 [error] <0.20814.0> Supervisor {<0.20814.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20815.0>, {amqp_params_network,<<"guest">>,<<"wCndrB9MPlrtLu8TxmwZ6aRvKpfMiIA1GvZ9fhC+EJwDfFpl9Pofo5kpWHTRGi...">>,...}) at <0.20816.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 03:51:22.079 [error] <0.20814.0> Supervisor {<0.20814.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20815.0>, {amqp_params_network,<<"guest">>,<<"wCndrB9MPlrtLu8TxmwZ6aRvKpfMiIA1GvZ9fhC+EJwDfFpl9Pofo5kpWHTRGi...">>,...}) at <0.20816.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 04:45:29.008 [error] <0.659.0> gen_server <0.659.0> terminated with reason: {socket_error,timeout}
2020-04-27 04:45:29.008 [error] <0.659.0> CRASH REPORT Process <0.659.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 04:45:29.009 [error] <0.654.0> Supervisor {<0.654.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.85>, <0.655.0>, <0.657.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62880 -> 127.0.0.1:5672">>) at <0.659.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 04:45:29.009 [error] <0.654.0> Supervisor {<0.654.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.85>, <0.655.0>, <0.657.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62880 -> 127.0.0.1:5672">>) at <0.659.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 04:45:29.025 [error] <0.655.0> gen_server <0.655.0> terminated with reason: {socket_error,timeout}
2020-04-27 04:45:29.025 [error] <0.655.0> CRASH REPORT Process <0.655.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 04:45:29.026 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.652.0> exit with reason shutdown in context child_terminated
2020-04-27 04:45:29.026 [error] <0.653.0> Supervisor {<0.653.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.654.0>, {amqp_params_network,<<"guest">>,<<"v4T3xPVVN5BpoZbDRp444uO1lYY/PaVP4BHB2dZ+yBGA1kgax0t0YOF5x/yIWM...">>,...}) at <0.655.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 04:45:29.026 [error] <0.653.0> Supervisor {<0.653.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.654.0>, {amqp_params_network,<<"guest">>,<<"v4T3xPVVN5BpoZbDRp444uO1lYY/PaVP4BHB2dZ+yBGA1kgax0t0YOF5x/yIWM...">>,...}) at <0.655.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 04:45:29.092 [error] <0.20831.0> gen_server <0.20831.0> terminated with reason: {socket_error,timeout}
2020-04-27 04:45:29.093 [error] <0.20831.0> CRASH REPORT Process <0.20831.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 04:45:29.095 [error] <0.20827.0> gen_server <0.20827.0> terminated with reason: {socket_error,timeout}
2020-04-27 04:45:29.095 [error] <0.20826.0> Supervisor {<0.20826.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.23>, <0.20827.0>, <0.20829.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62881 -> 127.0.0.1:5672">>) at <0.20831.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 04:45:29.096 [error] <0.20826.0> Supervisor {<0.20826.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.23>, <0.20827.0>, <0.20829.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62881 -> 127.0.0.1:5672">>) at <0.20831.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 04:45:29.098 [error] <0.20827.0> CRASH REPORT Process <0.20827.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 04:45:29.098 [error] <0.20825.0> Supervisor {<0.20825.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20826.0>, {amqp_params_network,<<"guest">>,<<"0bubonFFqGPIIafK8hnR+nB/7lXy42vvJk/6XrqA6uZvoqI+ZSxRUku7PV+0HK...">>,...}) at <0.20827.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 04:45:29.099 [error] <0.20825.0> Supervisor {<0.20825.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20826.0>, {amqp_params_network,<<"guest">>,<<"0bubonFFqGPIIafK8hnR+nB/7lXy42vvJk/6XrqA6uZvoqI+ZSxRUku7PV+0HK...">>,...}) at <0.20827.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 05:39:36.005 [error] <0.674.0> gen_server <0.674.0> terminated with reason: {socket_error,timeout}
2020-04-27 05:39:36.005 [error] <0.670.0> gen_server <0.670.0> terminated with reason: {socket_error,timeout}
2020-04-27 05:39:36.204 [error] <0.20843.0> gen_server <0.20843.0> terminated with reason: {socket_error,timeout}
2020-04-27 05:39:36.005 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 05:39:36.006 [error] <0.669.0> Supervisor {<0.669.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.86>, <0.670.0>, <0.672.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62909 -> 127.0.0.1:5672">>) at <0.674.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 05:39:36.006 [error] <0.669.0> Supervisor {<0.669.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.86>, <0.670.0>, <0.672.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62909 -> 127.0.0.1:5672">>) at <0.674.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 05:39:36.007 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.667.0> exit with reason shutdown in context child_terminated
2020-04-27 05:39:36.008 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 05:39:36.008 [error] <0.668.0> Supervisor {<0.668.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.669.0>, {amqp_params_network,<<"guest">>,<<"6tYiBXsnKiWjwIiNiUjBlDmroKq73pfIx8sL+yz7fhhpJVQD+QxIx/peh4SgSH...">>,...}) at <0.670.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 05:39:36.009 [error] <0.668.0> Supervisor {<0.668.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.669.0>, {amqp_params_network,<<"guest">>,<<"6tYiBXsnKiWjwIiNiUjBlDmroKq73pfIx8sL+yz7fhhpJVQD+QxIx/peh4SgSH...">>,...}) at <0.670.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 05:39:36.027 [error] <0.501.0> gen_server 'Elixir.Api.Supervisors.Connection' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.670.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in gen_server:call/3 line 223
2020-04-27 05:39:36.347 [error] <0.501.0> CRASH REPORT Process 'Elixir.Api.Supervisors.Connection' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.670.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in gen_server:call/3 line 223
2020-04-27 05:39:36.348 [error] <0.682.0> CRASH REPORT Process <0.682.0> with 0 neighbours exited with reason: {{{socket_error,timeout},{gen_server,call,[<0.670.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}},{'Elixir.GenServer',call,['Elixir.Api.Supervisors.Connection',open_channel,5000]}} in 'Elixir.GenServer':call/3 line 1009
2020-04-27 05:39:36.348 [error] <0.500.0> Supervisor {<0.500.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at <0.501.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.670.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in context child_terminated
2020-04-27 05:39:36.348 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.667.0> exit with reason {{{socket_error,timeout},{gen_server,call,[<0.670.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}},{'Elixir.GenServer',call,['Elixir.Api.Supervisors.Connection',open_channel,5000]}} in context start_error
2020-04-27 05:39:36.348 [error] <0.683.0>@Elixir.GenServer:call CRASH REPORT Process <0.683.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in 'Elixir.GenServer':call/3 line 999
2020-04-27 05:39:36.348 [error] <0.512.0>@Elixir.GenServer:call Supervisor {<0.512.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at {restarting,<0.667.0>} exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in context start_error
2020-04-27 05:39:36.204 [error] <0.20839.0> gen_server <0.20839.0> terminated with reason: {socket_error,timeout}
2020-04-27 05:39:36.204 [error] <0.20843.0> CRASH REPORT Process <0.20843.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 05:39:36.204 [error] <0.20839.0> CRASH REPORT Process <0.20839.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 05:39:36.204 [error] <0.20837.0> Supervisor {<0.20837.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20838.0>, {amqp_params_network,<<"guest">>,<<"BfI/Lc+j3GU6mjB2gnz2v30AIrQNYIuJ401Gmw913Wdx9dIh2CAEKUH1/mwTdx...">>,...}) at <0.20839.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 05:39:36.204 [error] <0.20837.0> Supervisor {<0.20837.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20838.0>, {amqp_params_network,<<"guest">>,<<"BfI/Lc+j3GU6mjB2gnz2v30AIrQNYIuJ401Gmw913Wdx9dIh2CAEKUH1/mwTdx...">>,...}) at <0.20839.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 05:39:36.206 [error] <0.20838.0> Supervisor {<0.20838.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.24>, <0.20839.0>, <0.20841.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62910 -> 127.0.0.1:5672">>) at <0.20843.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 05:39:36.206 [error] <0.20838.0> Supervisor {<0.20838.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.24>, <0.20839.0>, <0.20841.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62910 -> 127.0.0.1:5672">>) at <0.20843.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 06:33:43.009 [error] <0.691.0> gen_server <0.691.0> terminated with reason: {socket_error,timeout}
2020-04-27 06:33:43.009 [error] <0.691.0> CRASH REPORT Process <0.691.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 06:33:43.086 [error] <0.20855.0> gen_server <0.20855.0> terminated with reason: {socket_error,timeout}
2020-04-27 06:33:43.009 [error] <0.687.0> gen_server <0.687.0> terminated with reason: {socket_error,timeout}
2020-04-27 06:33:43.009 [error] <0.686.0> Supervisor {<0.686.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.87>, <0.687.0>, <0.689.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62927 -> 127.0.0.1:5672">>) at <0.691.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 06:33:43.088 [error] <0.20855.0> CRASH REPORT Process <0.20855.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 06:33:43.009 [error] <0.686.0> Supervisor {<0.686.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.87>, <0.687.0>, <0.689.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62927 -> 127.0.0.1:5672">>) at <0.691.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 06:33:43.089 [error] <0.20851.0> gen_server <0.20851.0> terminated with reason: {socket_error,timeout}
2020-04-27 06:33:43.010 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 06:33:43.010 [error] <0.695.0> Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.696.0> exit with reason shutdown in context child_terminated
2020-04-27 06:33:43.010 [error] <0.685.0> Supervisor {<0.685.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.686.0>, {amqp_params_network,<<"guest">>,<<"qM20RBVvYV0qvkVxphP8jJim7v22I8+XMgK2ymwnOFuF4MP7CPG06XHPtUcvDu...">>,...}) at <0.687.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 06:33:43.010 [error] <0.685.0> Supervisor {<0.685.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.686.0>, {amqp_params_network,<<"guest">>,<<"qM20RBVvYV0qvkVxphP8jJim7v22I8+XMgK2ymwnOFuF4MP7CPG06XHPtUcvDu...">>,...}) at <0.687.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 06:33:43.090 [error] <0.20850.0> Supervisor {<0.20850.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.25>, <0.20851.0>, <0.20853.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62926 -> 127.0.0.1:5672">>) at <0.20855.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 06:33:43.092 [error] <0.20850.0> Supervisor {<0.20850.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.25>, <0.20851.0>, <0.20853.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62926 -> 127.0.0.1:5672">>) at <0.20855.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 06:33:43.092 [error] <0.20851.0> CRASH REPORT Process <0.20851.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 06:33:43.095 [error] <0.20849.0> Supervisor {<0.20849.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20850.0>, {amqp_params_network,<<"guest">>,<<"8B/9x61RPiF8OKw0h1FUIytsoG9UAHpaoK4gyAN6yJ9BejZgehcUZO50F8j3Mi...">>,...}) at <0.20851.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 06:33:43.095 [error] <0.20849.0> Supervisor {<0.20849.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20850.0>, {amqp_params_network,<<"guest">>,<<"8B/9x61RPiF8OKw0h1FUIytsoG9UAHpaoK4gyAN6yJ9BejZgehcUZO50F8j3Mi...">>,...}) at <0.20851.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 06:33:43.096 [error] <0.20849.0> Supervisor {<0.20849.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.20850.0> exit with reason shutdown in context shutdown_error
2020-04-27 07:27:50.012 [error] <0.709.0> gen_server <0.709.0> terminated with reason: {socket_error,timeout}
2020-04-27 07:27:50.012 [error] <0.709.0> CRASH REPORT Process <0.709.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 07:27:50.012 [error] <0.705.0> gen_server <0.705.0> terminated with reason: {socket_error,timeout}
2020-04-27 07:27:50.013 [error] <0.704.0> Supervisor {<0.704.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.88>, <0.705.0>, <0.707.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62962 -> 127.0.0.1:5672">>) at <0.709.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 07:27:50.013 [error] <0.704.0> Supervisor {<0.704.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.88>, <0.705.0>, <0.707.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62962 -> 127.0.0.1:5672">>) at <0.709.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 07:27:50.013 [error] <0.705.0> CRASH REPORT Process <0.705.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 07:27:50.014 [error] <0.703.0> Supervisor {<0.703.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.704.0>, {amqp_params_network,<<"guest">>,<<"e2+r6tqhVAxo2dMMc1Ts6Abeno1VeSrkhhhBty8Fcmz1+jarIgq88y0BpnRafn...">>,...}) at <0.705.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 07:27:50.014 [error] <0.703.0> Supervisor {<0.703.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.704.0>, {amqp_params_network,<<"guest">>,<<"e2+r6tqhVAxo2dMMc1Ts6Abeno1VeSrkhhhBty8Fcmz1+jarIgq88y0BpnRafn...">>,...}) at <0.705.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 07:27:50.015 [error] <0.695.0> Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.702.0> exit with reason shutdown in context child_terminated
2020-04-27 08:21:57.016 [error] <0.724.0> gen_server <0.724.0> terminated with reason: {socket_error,timeout}
2020-04-27 08:21:57.189 [error] <0.20867.0> gen_server <0.20867.0> terminated with reason: {socket_error,timeout}
2020-04-27 08:21:57.016 [error] <0.724.0> CRASH REPORT Process <0.724.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 08:21:57.016 [error] <0.720.0> gen_server <0.720.0> terminated with reason: {socket_error,timeout}
2020-04-27 08:21:57.190 [error] <0.20867.0> CRASH REPORT Process <0.20867.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 08:21:57.019 [error] <0.719.0> Supervisor {<0.719.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.89>, <0.720.0>, <0.722.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62984 -> 127.0.0.1:5672">>) at <0.724.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 08:21:57.019 [error] <0.719.0> Supervisor {<0.719.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.89>, <0.720.0>, <0.722.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62984 -> 127.0.0.1:5672">>) at <0.724.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 08:21:57.024 [error] <0.695.0> Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.717.0> exit with reason shutdown in context child_terminated
2020-04-27 08:21:57.027 [error] <0.720.0> CRASH REPORT Process <0.720.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 08:21:57.027 [error] <0.718.0> Supervisor {<0.718.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.719.0>, {amqp_params_network,<<"guest">>,<<"DRttbSyogZxUrc0uTdYhYWnoF7K8zhsfhu8B8Mc60ATblWb49chw4UsYc9LuiP...">>,...}) at <0.720.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 08:21:57.028 [error] <0.684.0> gen_server 'Elixir.Api.Supervisors.Connection' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.720.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in gen_server:call/3 line 223
2020-04-27 08:21:57.029 [error] <0.718.0> Supervisor {<0.718.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.719.0>, {amqp_params_network,<<"guest">>,<<"DRttbSyogZxUrc0uTdYhYWnoF7K8zhsfhu8B8Mc60ATblWb49chw4UsYc9LuiP...">>,...}) at <0.720.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 08:21:57.193 [error] <0.20863.0> gen_server <0.20863.0> terminated with reason: {socket_error,timeout}
2020-04-27 08:21:57.029 [error] <0.684.0> CRASH REPORT Process 'Elixir.Api.Supervisors.Connection' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.720.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in gen_server:call/3 line 223
2020-04-27 08:21:57.194 [error] <0.20862.0> Supervisor {<0.20862.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.26>, <0.20863.0>, <0.20865.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62963 -> 127.0.0.1:5672">>) at <0.20867.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 08:21:57.029 [error] <0.732.0> CRASH REPORT Process <0.732.0> with 0 neighbours exited with reason: {{{socket_error,timeout},{gen_server,call,[<0.720.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}},{'Elixir.GenServer',call,['Elixir.Api.Supervisors.Connection',open_channel,5000]}} in 'Elixir.GenServer':call/3 line 1009
2020-04-27 08:21:57.194 [error] <0.20862.0> Supervisor {<0.20862.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.26>, <0.20863.0>, <0.20865.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62963 -> 127.0.0.1:5672">>) at <0.20867.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 08:21:57.030 [error] <0.695.0> Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.717.0> exit with reason {{{socket_error,timeout},{gen_server,call,[<0.720.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}},{'Elixir.GenServer',call,['Elixir.Api.Supervisors.Connection',open_channel,5000]}} in context start_error
2020-04-27 08:21:57.195 [error] <0.20863.0> CRASH REPORT Process <0.20863.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 08:21:57.030 [error] <0.733.0>@Elixir.GenServer:call CRASH REPORT Process <0.733.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in 'Elixir.GenServer':call/3 line 999
2020-04-27 08:21:57.195 [error] <0.20861.0> Supervisor {<0.20861.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20862.0>, {amqp_params_network,<<"guest">>,<<"108e3OPHGEbkcKu0+YIY7U29wfRTvnuAgn3hlhXPITtoO4rsiy4w3caKQbGGIF...">>,...}) at <0.20863.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 08:21:57.030 [error] <0.695.0>@Elixir.GenServer:call Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at {restarting,<0.717.0>} exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in context start_error
2020-04-27 08:21:57.196 [error] <0.20861.0> Supervisor {<0.20861.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20862.0>, {amqp_params_network,<<"guest">>,<<"108e3OPHGEbkcKu0+YIY7U29wfRTvnuAgn3hlhXPITtoO4rsiy4w3caKQbGGIF...">>,...}) at <0.20863.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 08:21:57.030 [error] <0.734.0>@Elixir.GenServer:call CRASH REPORT Process <0.734.0> with 0 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in 'Elixir.GenServer':call/3 line 999
2020-04-27 08:21:57.031 [error] <0.695.0>@Elixir.GenServer:call Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at {restarting,<0.717.0>} exit with reason no such process or port in call to 'Elixir.GenServer':call('Elixir.Api.Supervisors.Connection', open_channel, 5000) in context start_error
2020-04-27 08:21:57.031 [error] <0.695.0> Supervisor {<0.695.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at {restarting,<0.717.0>} exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 08:21:57.031 [error] <0.500.0> Supervisor {<0.500.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at <0.684.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.720.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},60000]}} in context child_terminated
2020-04-27 08:21:57.031 [error] <0.500.0> Supervisor {<0.500.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Worker' started with 'Elixir.Api.Supervisors.Worker':start_link([]) at <0.694.0> exit with reason noproc in context shutdown_error
2020-04-27 09:15:00.018 [error] <0.742.0> gen_server <0.742.0> terminated with reason: {socket_error,timeout}
2020-04-27 09:15:00.071 [error] <0.20882.0> gen_server <0.20882.0> terminated with reason: {socket_error,timeout}
2020-04-27 09:15:00.018 [error] <0.742.0> CRASH REPORT Process <0.742.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 09:15:00.020 [error] <0.738.0> gen_server <0.738.0> terminated with reason: {socket_error,timeout}
2020-04-27 09:15:00.071 [error] <0.20882.0> CRASH REPORT Process <0.20882.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 09:15:00.021 [error] <0.738.0> CRASH REPORT Process <0.738.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 09:15:00.021 [error] <0.736.0> Supervisor {<0.736.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.737.0>, {amqp_params_network,<<"guest">>,<<"JW6nLHAQkJeP45BvGwtVzkCm15F1RL+Lyg9TSqmo9VHiB+7tZW9HwCwN43Sapn...">>,...}) at <0.738.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 09:15:00.072 [error] <0.20878.0> gen_server <0.20878.0> terminated with reason: {socket_error,timeout}
2020-04-27 09:15:00.021 [error] <0.736.0> Supervisor {<0.736.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.737.0>, {amqp_params_network,<<"guest">>,<<"JW6nLHAQkJeP45BvGwtVzkCm15F1RL+Lyg9TSqmo9VHiB+7tZW9HwCwN43Sapn...">>,...}) at <0.738.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 09:15:00.021 [error] <0.737.0> Supervisor {<0.737.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.90>, <0.738.0>, <0.740.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63008 -> 127.0.0.1:5672">>) at <0.742.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 09:15:00.021 [error] <0.737.0> Supervisor {<0.737.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.90>, <0.738.0>, <0.740.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63008 -> 127.0.0.1:5672">>) at <0.742.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 09:15:00.022 [error] <0.746.0> Supervisor {<0.746.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.747.0> exit with reason shutdown in context child_terminated
2020-04-27 09:15:00.074 [error] <0.20878.0> CRASH REPORT Process <0.20878.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 09:15:00.075 [error] <0.20877.0> Supervisor {<0.20877.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.27>, <0.20878.0>, <0.20880.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63009 -> 127.0.0.1:5672">>) at <0.20882.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 09:15:00.075 [error] <0.20877.0> Supervisor {<0.20877.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.27>, <0.20878.0>, <0.20880.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63009 -> 127.0.0.1:5672">>) at <0.20882.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 09:15:00.075 [error] <0.20876.0> Supervisor {<0.20876.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20877.0>, {amqp_params_network,<<"guest">>,<<"hYQgsCVe2DwIhr2oaz7ubG2fV2BGESHSG43NbW3BKB6Txvl0j2Jiy+D2RzZ3DZ...">>,...}) at <0.20878.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 09:15:00.075 [error] <0.20876.0> Supervisor {<0.20876.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20877.0>, {amqp_params_network,<<"guest">>,<<"hYQgsCVe2DwIhr2oaz7ubG2fV2BGESHSG43NbW3BKB6Txvl0j2Jiy+D2RzZ3DZ...">>,...}) at <0.20878.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 09:26:23.307 [error] <0.20890.0> gen_server <0.20890.0> terminated with reason: socket_closed_unexpectedly
2020-04-27 09:26:23.311 [error] <0.20890.0> CRASH REPORT Process <0.20890.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-04-27 09:26:23.311 [error] <0.20888.0> Supervisor {<0.20888.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20889.0>, {amqp_params_network,<<"guest">>,<<"hxKY4moN+bXTabxAmdQvbr8rEFWXvY404spPqYpVZ/lArDttOgpPmLJgHgqttz...">>,...}) at <0.20890.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-04-27 09:26:23.311 [error] <0.20888.0> Supervisor {<0.20888.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20889.0>, {amqp_params_network,<<"guest">>,<<"hxKY4moN+bXTabxAmdQvbr8rEFWXvY404spPqYpVZ/lArDttOgpPmLJgHgqttz...">>,...}) at <0.20890.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:10:26.029 [error] <0.20924.0> gen_server <0.20924.0> terminated with reason: socket_closed_unexpectedly
2020-04-27 10:10:26.032 [error] <0.20924.0> CRASH REPORT Process <0.20924.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-04-27 10:10:26.034 [error] <0.20922.0> Supervisor {<0.20922.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20923.0>, {amqp_params_network,<<"guest">>,<<"sEcDm8UfQp9G1+ntNDFE/1y2QaDlk1lsvDy15RTNhFQtevW932yeGQwJOFYXVW...">>,...}) at <0.20924.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-04-27 10:10:26.037 [error] <0.20922.0> Supervisor {<0.20922.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.20923.0>, {amqp_params_network,<<"guest">>,<<"sEcDm8UfQp9G1+ntNDFE/1y2QaDlk1lsvDy15RTNhFQtevW932yeGQwJOFYXVW...">>,...}) at <0.20924.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:17:44.014 [error] <0.760.0> gen_server <0.760.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:17:44.014 [error] <0.760.0> CRASH REPORT Process <0.760.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:17:44.014 [error] <0.756.0> gen_server <0.756.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:17:44.015 [error] <0.755.0> Supervisor {<0.755.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.91>, <0.756.0>, <0.758.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63025 -> 127.0.0.1:5672">>) at <0.760.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:17:44.020 [error] <0.755.0> Supervisor {<0.755.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.91>, <0.756.0>, <0.758.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63025 -> 127.0.0.1:5672">>) at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:17:44.020 [error] <0.756.0> CRASH REPORT Process <0.756.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:17:44.021 [error] <0.754.0> Supervisor {<0.754.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.755.0>, {amqp_params_network,<<"guest">>,<<"dhMp5L+cxz/N3YylAp+/eayhMp49vFrpQuozL1nbxAB2a7mwJR5EGdZOhZ5hgH...">>,...}) at <0.756.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:17:44.021 [error] <0.754.0> Supervisor {<0.754.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.755.0>, {amqp_params_network,<<"guest">>,<<"dhMp5L+cxz/N3YylAp+/eayhMp49vFrpQuozL1nbxAB2a7mwJR5EGdZOhZ5hgH...">>,...}) at <0.756.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:17:44.022 [error] <0.746.0> Supervisor {<0.746.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.753.0> exit with reason shutdown in context child_terminated
2020-04-27 10:17:44.195 [error] <0.21037.0> gen_server <0.21037.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:17:44.195 [error] <0.21037.0> CRASH REPORT Process <0.21037.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:17:44.200 [error] <0.21033.0> gen_server <0.21033.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:17:44.201 [error] <0.21032.0> Supervisor {<0.21032.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.30>, <0.21033.0>, <0.21035.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63283 -> 127.0.0.1:5672">>) at <0.21037.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:17:44.202 [error] <0.21032.0> Supervisor {<0.21032.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.30>, <0.21033.0>, <0.21035.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63283 -> 127.0.0.1:5672">>) at <0.21037.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:17:44.202 [error] <0.21033.0> CRASH REPORT Process <0.21033.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:17:44.202 [error] <0.21031.0> Supervisor {<0.21031.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21032.0>, {amqp_params_network,<<"guest">>,<<"DPY9fTfmIM8KvZSJU/ScWlylAwdznXHi79+qKPud0iDrTGRRf/82gWnipSOX6G...">>,...}) at <0.21033.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:17:44.202 [error] <0.21031.0> Supervisor {<0.21031.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21032.0>, {amqp_params_network,<<"guest">>,<<"DPY9fTfmIM8KvZSJU/ScWlylAwdznXHi79+qKPud0iDrTGRRf/82gWnipSOX6G...">>,...}) at <0.21033.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:55:42.019 [error] <0.801.0> gen_server <0.801.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:55:42.019 [error] <0.805.0> gen_server <0.805.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:55:42.115 [error] <0.21058.0> gen_server <0.21058.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:55:42.019 [error] <0.805.0> CRASH REPORT Process <0.805.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:55:42.020 [error] <0.800.0> Supervisor {<0.800.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.92>, <0.801.0>, <0.803.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63310 -> 127.0.0.1:5672">>) at <0.805.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:55:42.020 [error] <0.800.0> Supervisor {<0.800.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.92>, <0.801.0>, <0.803.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63310 -> 127.0.0.1:5672">>) at <0.805.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:55:42.020 [error] <0.801.0> CRASH REPORT Process <0.801.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:55:42.020 [error] <0.799.0> Supervisor {<0.799.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.800.0>, {amqp_params_network,<<"guest">>,<<"zGZAiNpLWosK2Ifa9KGvHHwxH8OxZ+V06uNjcOX6cpe6uBXaukCbnSc4z5DzwT...">>,...}) at <0.801.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:55:42.020 [error] <0.799.0> Supervisor {<0.799.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.800.0>, {amqp_params_network,<<"guest">>,<<"zGZAiNpLWosK2Ifa9KGvHHwxH8OxZ+V06uNjcOX6cpe6uBXaukCbnSc4z5DzwT...">>,...}) at <0.801.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:55:42.020 [error] <0.746.0> Supervisor {<0.746.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Publisher' started with 'Elixir.Api.Supervisors.Publisher':start_link([]) at <0.798.0> exit with reason shutdown in context child_terminated
2020-04-27 10:55:42.115 [error] <0.21058.0> CRASH REPORT Process <0.21058.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:55:42.116 [error] <0.21053.0> Supervisor {<0.21053.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.31>, <0.21054.0>, <0.21056.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63311 -> 127.0.0.1:5672">>) at <0.21058.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:55:42.116 [error] <0.21054.0> gen_server <0.21054.0> terminated with reason: {socket_error,timeout}
2020-04-27 10:55:42.117 [error] <0.21053.0> Supervisor {<0.21053.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.31>, <0.21054.0>, <0.21056.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63311 -> 127.0.0.1:5672">>) at <0.21058.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 10:55:42.121 [error] <0.21054.0> CRASH REPORT Process <0.21054.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-27 10:55:42.121 [error] <0.21052.0> Supervisor {<0.21052.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21053.0>, {amqp_params_network,<<"guest">>,<<"op9+umBytqoJs9FRZHKZ66GDDtZ2qrmyEz2E4rcziKvERHqG7tqqLWh9e4qX+w...">>,...}) at <0.21054.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-27 10:55:42.121 [error] <0.21052.0> Supervisor {<0.21052.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21053.0>, {amqp_params_network,<<"guest">>,<<"op9+umBytqoJs9FRZHKZ66GDDtZ2qrmyEz2E4rcziKvERHqG7tqqLWh9e4qX+w...">>,...}) at <0.21054.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-27 12:37:25.297 [error] <0.21595.0>@observer_wx:init:106 CRASH REPORT Process <0.21595.0> with 0 neighbours exited with reason: bad argument in call to erlang:register(observer, <0.21595.0>) in observer_wx:init/1 line 106
2020-04-27 13:18:22.505 [error] <0.21065.0> gen_server <0.21065.0> terminated with reason: socket_closed_unexpectedly
2020-04-27 13:18:22.511 [error] <0.21065.0> CRASH REPORT Process <0.21065.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2020-04-27 13:18:22.512 [error] <0.21063.0> Supervisor {<0.21063.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21064.0>, {amqp_params_network,<<"guest">>,<<"p1Iq0TZfcvazzytUG/hemADyc8zjp7dElP08hGoF5iuCHVdCtC8IH9M/rNHP/0...">>,...}) at <0.21065.0> exit with reason socket_closed_unexpectedly in context child_terminated
2020-04-27 13:18:22.512 [error] <0.21063.0> Supervisor {<0.21063.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.21064.0>, {amqp_params_network,<<"guest">>,<<"p1Iq0TZfcvazzytUG/hemADyc8zjp7dElP08hGoF5iuCHVdCtC8IH9M/rNHP/0...">>,...}) at <0.21065.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-28 00:33:20.465 [error] <0.379.0>@credentials_obfuscation_pbe:pad:137 CRASH REPORT Process <0.379.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137
2020-04-28 00:33:20.465 [error] <0.378.0>@credentials_obfuscation_pbe:pad:137 Supervisor {<0.378.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137 in context start_error
2020-04-28 00:33:20.469 [error] <0.347.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src/amqp_connection.erl"},{line,169}]},{'Elixir.AMQP.Connection',do_open,2,...},...]}}} in context start_error
2020-04-28 00:33:20.474 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src..."},...]},...]}}}}},...} in application_master:init/4 line 138
2020-04-28 00:33:31.799 [error] <0.481.0>@credentials_obfuscation_pbe:pad:137 Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137 in context start_error
2020-04-28 00:33:31.800 [error] <0.347.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src/amqp_connection.erl"},{line,169}]},{'Elixir.AMQP.Connection',do_open,2,...},...]}}} in context start_error
2020-04-28 00:33:31.822 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src..."},...]},...]}}}}},...} in application_master:init/4 line 138
2020-04-28 02:19:59.478 [error] <0.379.0>@credentials_obfuscation_pbe:pad:137 CRASH REPORT Process <0.379.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137
2020-04-28 02:19:59.478 [error] <0.378.0>@credentials_obfuscation_pbe:pad:137 Supervisor {<0.378.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137 in context start_error
2020-04-28 02:19:59.479 [error] <0.347.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src/amqp_connection.erl"},{line,169}]},{'Elixir.AMQP.Connection',do_open,2,...},...]}}} in context start_error
2020-04-28 02:19:59.491 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src..."},...]},...]}}}}},...} in application_master:init/4 line 138
2020-04-28 02:20:13.546 [error] <0.482.0>@credentials_obfuscation_pbe:pad:137 CRASH REPORT Process <0.482.0> with 0 neighbours crashed with reason: bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137
2020-04-28 02:20:13.547 [error] <0.481.0>@credentials_obfuscation_pbe:pad:137 Supervisor {<0.481.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason bad argument in call to erlang:byte_size(nil) in credentials_obfuscation_pbe:pad/2 line 137 in context start_error
2020-04-28 02:20:13.547 [error] <0.347.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src/amqp_connection.erl"},{line,169}]},{'Elixir.AMQP.Connection',do_open,2,...},...]}}} in context start_error
2020-04-28 02:20:13.566 [error] <0.345.0> CRASH REPORT Process <0.345.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{badarg,[{erlang,byte_size,[nil],[]},{credentials_obfuscation_pbe,pad,2,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,137}]},{credentials_obfuscation_pbe,encrypt,5,[{file,"/app/deps/credentials_obfuscation/src/credentials_obfuscation_pbe.erl"},{line,107}]},{amqp_connection,start,2,[{file,"/app/deps/amqp_client/src..."},...]},...]}}}}},...} in application_master:init/4 line 138
