2020-04-26 07:03:20.958 [error] <0.418.0> Supervisor {<0.418.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.464.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context start_error
2020-04-26 07:03:20.959 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.464.0>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.IO',puts,2,[{file,"lib/io.ex"},{line,669}]},{'Elixir.Api.Supervisors.Connection',...},...]}}} in context start_error
2020-04-26 07:03:20.969 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.464.0>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},...]}}}}},...} in application_master:init/4 line 138
2020-04-26 07:03:24.922 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.459.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-04-26 07:03:24.923 [error] <0.455.0> Supervisor {<0.455.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.459.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context start_error
2020-04-26 07:03:28.456 [error] <0.522.0> CRASH REPORT Process <0.522.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.525.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-04-26 07:03:28.456 [error] <0.521.0> Supervisor {<0.521.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.525.0>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context start_error
2020-04-26 07:03:28.457 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.525.0>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},{'Elixir.IO',puts,2,[{file,"lib/io.ex"},{line,669}]},{'Elixir.Api.Supervisors.Connection',...},...]}}} in context start_error
2020-04-26 07:03:28.481 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.525.0>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"lib/string/chars.ex"},{line,22}]},...]}}}}},...} in application_master:init/4 line 138
2020-04-26 07:50:12.460 [error] <0.458.0>@amqp_gen_connection:terminate:242 gen_server <0.458.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.457.0>,{amqp_params_network,nil,<<"68zmC1Ec7NKTHpA+AvVqnScJF3ARsu6z7KcZMWoM5OwTg+VyPk1ENdBuYza...">>,...}}) line 242
2020-04-26 07:50:12.583 [error] <0.458.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.458.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.457.0>,{amqp_params_network,nil,<<"68zmC1Ec7NKTHpA+AvVqnScJF3ARsu6z7KcZMWoM5OwTg+VyPk1ENdBuYza...">>,...}}) line 242
2020-04-26 07:50:12.584 [error] <0.456.0>@amqp_gen_connection:terminate:242 Supervisor {<0.456.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.457.0>, {amqp_params_network,nil,<<"68zmC1Ec7NKTHpA+AvVqnScJF3ARsu6z7KcZMWoM5OwTg+VyPk1ENdBuYzaQyd/Y">>,...}) at <0.458.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.457.0>,{amqp_params_network,nil,<<"68zmC1Ec7NKTHpA+AvVqnScJF3ARsu6z7KcZMWoM5OwTg+VyPk1ENdBuYza...">>,...}}) line 242 in context child_terminated
2020-04-26 07:50:12.588 [error] <0.456.0> Supervisor {<0.456.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.457.0>, {amqp_params_network,nil,<<"68zmC1Ec7NKTHpA+AvVqnScJF3ARsu6z7KcZMWoM5OwTg+VyPk1ENdBuYzaQyd/Y">>,...}) at <0.458.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:50:12.588 [error] <0.419.0> CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in gen_server:call/3 line 223
2020-04-26 07:50:12.589 [error] <0.418.0> Supervisor {<0.418.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 07:50:12.596 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_clien..."},...]},...]},...],...},...]},...}}} in context start_error
2020-04-26 07:50:12.597 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},...]},...],...},...]},...}}}}},...} in application_master:init/4 line 138
2020-04-26 07:50:17.220 [error] <0.449.0>@amqp_gen_connection:terminate:242 gen_server <0.449.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.448.0>,{amqp_params_network,nil,<<"Juj+dvyRXuGUqnw+n7dAPsKxyzLxCZP3nKQz7acjEsylsIcybflrbnemwWs...">>,...}}) line 242
2020-04-26 07:50:17.277 [error] <0.449.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.449.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.448.0>,{amqp_params_network,nil,<<"Juj+dvyRXuGUqnw+n7dAPsKxyzLxCZP3nKQz7acjEsylsIcybflrbnemwWs...">>,...}}) line 242
2020-04-26 07:50:17.279 [error] <0.447.0>@amqp_gen_connection:terminate:242 Supervisor {<0.447.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.448.0>, {amqp_params_network,nil,<<"Juj+dvyRXuGUqnw+n7dAPsKxyzLxCZP3nKQz7acjEsylsIcybflrbnemwWsi9JoM">>,...}) at <0.449.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.448.0>,{amqp_params_network,nil,<<"Juj+dvyRXuGUqnw+n7dAPsKxyzLxCZP3nKQz7acjEsylsIcybflrbnemwWs...">>,...}}) line 242 in context child_terminated
2020-04-26 07:50:17.280 [error] <0.447.0> Supervisor {<0.447.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.448.0>, {amqp_params_network,nil,<<"Juj+dvyRXuGUqnw+n7dAPsKxyzLxCZP3nKQz7acjEsylsIcybflrbnemwWsi9JoM">>,...}) at <0.449.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:50:17.282 [error] <0.446.0> CRASH REPORT Process <0.446.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in gen_server:call/3 line 223
2020-04-26 07:50:17.285 [error] <0.445.0> Supervisor {<0.445.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 07:50:20.166 [error] <0.525.0>@amqp_gen_connection:terminate:242 gen_server <0.525.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"2AB67N1LzNZHugMenYDLnDLccc7mwyLLknJNMD6sYc8XeLgQ+SPokmg3UTQ...">>,...}}) line 242
2020-04-26 07:50:20.212 [error] <0.525.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.525.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"2AB67N1LzNZHugMenYDLnDLccc7mwyLLknJNMD6sYc8XeLgQ+SPokmg3UTQ...">>,...}}) line 242
2020-04-26 07:50:20.217 [error] <0.523.0>@amqp_gen_connection:terminate:242 Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"2AB67N1LzNZHugMenYDLnDLccc7mwyLLknJNMD6sYc8XeLgQ+SPokmg3UTQM7F0s">>,...}) at <0.525.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"2AB67N1LzNZHugMenYDLnDLccc7mwyLLknJNMD6sYc8XeLgQ+SPokmg3UTQ...">>,...}}) line 242 in context child_terminated
2020-04-26 07:50:20.217 [error] <0.523.0> Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"2AB67N1LzNZHugMenYDLnDLccc7mwyLLknJNMD6sYc8XeLgQ+SPokmg3UTQM7F0s">>,...}) at <0.525.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:50:20.218 [error] <0.521.0> Supervisor {<0.521.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 07:50:20.219 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_clien..."},...]},...]},...],...},...]},...}}} in context start_error
2020-04-26 07:50:20.222 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},...]},...],...},...]},...}}}}},...} in application_master:init/4 line 138
2020-04-26 07:58:07.882 [error] <0.452.0>@amqp_gen_connection:terminate:242 gen_server <0.452.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.451.0>,{amqp_params_network,nil,<<"4HdWJ6Ex2S4q1LYCE8Q31FpWlkqd2GtPZelqjWunmcRnAiQcME//j2A50yV...">>,...}}) line 242
2020-04-26 07:58:07.999 [error] <0.452.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.452.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.451.0>,{amqp_params_network,nil,<<"4HdWJ6Ex2S4q1LYCE8Q31FpWlkqd2GtPZelqjWunmcRnAiQcME//j2A50yV...">>,...}}) line 242
2020-04-26 07:58:08.011 [error] <0.450.0>@amqp_gen_connection:terminate:242 Supervisor {<0.450.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.451.0>, {amqp_params_network,nil,<<"4HdWJ6Ex2S4q1LYCE8Q31FpWlkqd2GtPZelqjWunmcRnAiQcME//j2A50yVvO0VI">>,...}) at <0.452.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.451.0>,{amqp_params_network,nil,<<"4HdWJ6Ex2S4q1LYCE8Q31FpWlkqd2GtPZelqjWunmcRnAiQcME//j2A50yV...">>,...}}) line 242 in context child_terminated
2020-04-26 07:58:08.021 [error] <0.450.0> Supervisor {<0.450.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.451.0>, {amqp_params_network,nil,<<"4HdWJ6Ex2S4q1LYCE8Q31FpWlkqd2GtPZelqjWunmcRnAiQcME//j2A50yVvO0VI">>,...}) at <0.452.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:58:08.035 [error] <0.419.0> CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in gen_server:call/3 line 223
2020-04-26 07:58:08.035 [error] <0.418.0> Supervisor {<0.418.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 07:58:08.036 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_clien..."},...]},...]},...],...},...]},...}}} in context start_error
2020-04-26 07:58:08.044 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},...]},...],...},...]},...}}}}},...} in application_master:init/4 line 138
2020-04-26 07:58:13.844 [error] <0.444.0>@amqp_gen_connection:terminate:242 gen_server <0.444.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"3+47uEupunk47mn69XBI5Z+Sk5lGcbrroWj3UFW6ZgpFy8T5vuutmxtIPEw...">>,...}}) line 242
2020-04-26 07:58:13.866 [error] <0.444.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"3+47uEupunk47mn69XBI5Z+Sk5lGcbrroWj3UFW6ZgpFy8T5vuutmxtIPEw...">>,...}}) line 242
2020-04-26 07:58:13.867 [error] <0.442.0>@amqp_gen_connection:terminate:242 Supervisor {<0.442.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.443.0>, {amqp_params_network,nil,<<"3+47uEupunk47mn69XBI5Z+Sk5lGcbrroWj3UFW6ZgpFy8T5vuutmxtIPEwhf2/G">>,...}) at <0.444.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"3+47uEupunk47mn69XBI5Z+Sk5lGcbrroWj3UFW6ZgpFy8T5vuutmxtIPEw...">>,...}}) line 242 in context child_terminated
2020-04-26 07:58:13.872 [error] <0.442.0> Supervisor {<0.442.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.443.0>, {amqp_params_network,nil,<<"3+47uEupunk47mn69XBI5Z+Sk5lGcbrroWj3UFW6ZgpFy8T5vuutmxtIPEwhf2/G">>,...}) at <0.444.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:58:16.606 [error] <0.525.0>@amqp_gen_connection:terminate:242 gen_server <0.525.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"8HYGru1YXYgLFU5+MOcltXn2KbNBrZXhigntm7VAOYuwqpkT8pMM/yGcSeD...">>,...}}) line 242
2020-04-26 07:58:16.632 [error] <0.525.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.525.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"8HYGru1YXYgLFU5+MOcltXn2KbNBrZXhigntm7VAOYuwqpkT8pMM/yGcSeD...">>,...}}) line 242
2020-04-26 07:58:16.638 [error] <0.523.0>@amqp_gen_connection:terminate:242 Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"8HYGru1YXYgLFU5+MOcltXn2KbNBrZXhigntm7VAOYuwqpkT8pMM/yGcSeDB8DvO">>,...}) at <0.525.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"8HYGru1YXYgLFU5+MOcltXn2KbNBrZXhigntm7VAOYuwqpkT8pMM/yGcSeD...">>,...}}) line 242 in context child_terminated
2020-04-26 07:58:16.639 [error] <0.523.0> Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"8HYGru1YXYgLFU5+MOcltXn2KbNBrZXhigntm7VAOYuwqpkT8pMM/yGcSeDB8DvO">>,...}) at <0.525.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 07:58:16.640 [error] <0.521.0> Supervisor {<0.521.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 07:58:16.640 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_clien..."},...]},...]},...],...},...]},...}}} in context start_error
2020-04-26 07:58:16.649 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},...]},...],...},...]},...}}}}},...} in application_master:init/4 line 138
2020-04-26 08:00:23.827 [error] <0.455.0>@amqp_gen_connection:terminate:242 gen_server <0.455.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.454.0>,{amqp_params_network,nil,<<"ZNzvQ2akBEgZpPtWlsZZqJV1ho1mTHV1pjz4/K7cP7Lh5tCwZUhs2c+butt...">>,...}}) line 242
2020-04-26 08:00:23.935 [error] <0.455.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.455.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.454.0>,{amqp_params_network,nil,<<"ZNzvQ2akBEgZpPtWlsZZqJV1ho1mTHV1pjz4/K7cP7Lh5tCwZUhs2c+butt...">>,...}}) line 242
2020-04-26 08:00:23.940 [error] <0.453.0>@amqp_gen_connection:terminate:242 Supervisor {<0.453.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.454.0>, {amqp_params_network,nil,<<"ZNzvQ2akBEgZpPtWlsZZqJV1ho1mTHV1pjz4/K7cP7Lh5tCwZUhs2c+buttjvXqs">>,...}) at <0.455.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.454.0>,{amqp_params_network,nil,<<"ZNzvQ2akBEgZpPtWlsZZqJV1ho1mTHV1pjz4/K7cP7Lh5tCwZUhs2c+butt...">>,...}}) line 242 in context child_terminated
2020-04-26 08:00:23.941 [error] <0.453.0> Supervisor {<0.453.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.454.0>, {amqp_params_network,nil,<<"ZNzvQ2akBEgZpPtWlsZZqJV1ho1mTHV1pjz4/K7cP7Lh5tCwZUhs2c+buttjvXqs">>,...}) at <0.455.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-26 08:00:23.952 [error] <0.419.0> CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in gen_server:call/3 line 223
2020-04-26 08:00:23.953 [error] <0.418.0> Supervisor {<0.418.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Api.Supervisors.Connection' started with 'Elixir.Api.Supervisors.Connection':start_link([]) at undefined exit with reason {{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,184}]},{amqp_gen_connection,...},...]},...],...},...]},...} in context start_error
2020-04-26 08:00:23.961 [error] <0.387.0> Supervisor 'Elixir.Api.Supervisor' had child 'Elixir.Api.Supervisors.Supervisor' started with 'Elixir.Api.Supervisors.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},{amqp_network_connection,try_handshake,3,[{file,"/app/deps/amqp_clien..."},...]},...]},...],...},...]},...}}} in context start_error
2020-04-26 08:00:23.984 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Api.Supervisors.Connection',{{function_clause,[{amqp_gen_connection,terminate,[{badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,login,3,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,277}]},{amqp_network_connection,network_handshake,2,[{file,"/app/deps/amqp_client/src/amqp_network_connection.erl"},{line,204}]},...]},...],...},...]},...}}}}},...} in application_master:init/4 line 138
2020-04-26 08:00:29.693 [error] <0.444.0>@amqp_gen_connection:terminate:242 gen_server <0.444.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"JmRZ914ZltyOkEacnJCL8TaPHBZqQpmQx50Mlsrw5RHkw6DLf6fMWjU+Vwq...">>,...}}) line 242
2020-04-26 08:00:29.732 [error] <0.444.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.444.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"JmRZ914ZltyOkEacnJCL8TaPHBZqQpmQx50Mlsrw5RHkw6DLf6fMWjU+Vwq...">>,...}}) line 242
2020-04-26 08:00:29.734 [error] <0.442.0>@amqp_gen_connection:terminate:242 Supervisor {<0.442.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.443.0>, {amqp_params_network,nil,<<"JmRZ914ZltyOkEacnJCL8TaPHBZqQpmQx50Mlsrw5RHkw6DLf6fMWjU+Vwqq2ORo">>,...}) at <0.444.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.443.0>,{amqp_params_network,nil,<<"JmRZ914ZltyOkEacnJCL8TaPHBZqQpmQx50Mlsrw5RHkw6DLf6fMWjU+Vwq...">>,...}}) line 242 in context child_terminated
2020-04-26 08:00:32.649 [error] <0.525.0>@amqp_gen_connection:terminate:242 gen_server <0.525.0> terminated with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"wVXbpL1iEg/gEkKvCmNQJa7o/OrTIjsGfI48Osg1PdDXgB32Nfbp8W9ZSNl...">>,...}}) line 242
2020-04-26 08:00:32.675 [error] <0.525.0>@amqp_gen_connection:terminate:242 CRASH REPORT Process <0.525.0> with 0 neighbours crashed with reason: no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"wVXbpL1iEg/gEkKvCmNQJa7o/OrTIjsGfI48Osg1PdDXgB32Nfbp8W9ZSNl...">>,...}}) line 242
2020-04-26 08:00:32.677 [error] <0.523.0>@amqp_gen_connection:terminate:242 Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"wVXbpL1iEg/gEkKvCmNQJa7o/OrTIjsGfI48Osg1PdDXgB32Nfbp8W9ZSNlQx7mz">>,...}) at <0.525.0> exit with reason no function clause matching amqp_gen_connection:terminate({badarg,[{erlang,byte_size,[nil],[]},{amqp_auth_mechanisms,plain,3,[]},{amqp_network_connection,...},...]}, {<0.524.0>,{amqp_params_network,nil,<<"wVXbpL1iEg/gEkKvCmNQJa7o/OrTIjsGfI48Osg1PdDXgB32Nfbp8W9ZSNl...">>,...}}) line 242 in context child_terminated
2020-04-26 08:00:32.678 [error] <0.523.0> Supervisor {<0.523.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.524.0>, {amqp_params_network,nil,<<"wVXbpL1iEg/gEkKvCmNQJa7o/OrTIjsGfI48Osg1PdDXgB32Nfbp8W9ZSNlQx7mz">>,...}) at <0.525.0> exit with reason reached_max_restart_intensity in context shutdown
